// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: schemas/samples/hello/v1alpha1/hello.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/yolocs/ce-proto/pkg/eventtypes/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GreetingWord   string `protobuf:"bytes,1,opt,name=greeting_word,json=greetingWord,proto3" json:"greeting_word,omitempty"`
	GreetingTarget string `protobuf:"bytes,2,opt,name=greeting_target,json=greetingTarget,proto3" json:"greeting_target,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schemas_samples_hello_v1alpha1_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_samples_hello_v1alpha1_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_schemas_samples_hello_v1alpha1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetGreetingWord() string {
	if x != nil {
		return x.GreetingWord
	}
	return ""
}

func (x *Hello) GetGreetingTarget() string {
	if x != nil {
		return x.GreetingTarget
	}
	return ""
}

var File_schemas_samples_hello_v1alpha1_hello_proto protoreflect.FileDescriptor

var file_schemas_samples_hello_v1alpha1_hello_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x1a, 0x20, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x23,
	0x0a, 0x0d, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x57,
	0x6f, 0x72, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x3a, 0x08, 0x8a, 0x88,
	0x27, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f, 0x6c, 0x6f, 0x63, 0x73, 0x2f, 0x63, 0x65, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_schemas_samples_hello_v1alpha1_hello_proto_rawDescOnce sync.Once
	file_schemas_samples_hello_v1alpha1_hello_proto_rawDescData = file_schemas_samples_hello_v1alpha1_hello_proto_rawDesc
)

func file_schemas_samples_hello_v1alpha1_hello_proto_rawDescGZIP() []byte {
	file_schemas_samples_hello_v1alpha1_hello_proto_rawDescOnce.Do(func() {
		file_schemas_samples_hello_v1alpha1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_schemas_samples_hello_v1alpha1_hello_proto_rawDescData)
	})
	return file_schemas_samples_hello_v1alpha1_hello_proto_rawDescData
}

var file_schemas_samples_hello_v1alpha1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_samples_hello_v1alpha1_hello_proto_goTypes = []interface{}{
	(*Hello)(nil), // 0: sample.hello.v1alpha1.Hello
}
var file_schemas_samples_hello_v1alpha1_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schemas_samples_hello_v1alpha1_hello_proto_init() }
func file_schemas_samples_hello_v1alpha1_hello_proto_init() {
	if File_schemas_samples_hello_v1alpha1_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schemas_samples_hello_v1alpha1_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schemas_samples_hello_v1alpha1_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_samples_hello_v1alpha1_hello_proto_goTypes,
		DependencyIndexes: file_schemas_samples_hello_v1alpha1_hello_proto_depIdxs,
		MessageInfos:      file_schemas_samples_hello_v1alpha1_hello_proto_msgTypes,
	}.Build()
	File_schemas_samples_hello_v1alpha1_hello_proto = out.File
	file_schemas_samples_hello_v1alpha1_hello_proto_rawDesc = nil
	file_schemas_samples_hello_v1alpha1_hello_proto_goTypes = nil
	file_schemas_samples_hello_v1alpha1_hello_proto_depIdxs = nil
}
